[package]
name = "turlio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "turlio"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.25.0"
serde = "1.0.219"
serde_json = "1.0.140"
